version: '3.8'

services:
    mongo_launcher:
        container_name: mongo_launcher
        image: mongo:5.0.9
        restart: on-failure
        networks:
            - mongo_network
        volumes:
            - ./docker/scripts/mongo-setup.sh:/scripts/mongo-setup.sh
        entrypoint: ['sh', '/scripts/mongo-setup.sh']
    mongo_replica_1:
        container_name: mongo_replica_1
        image: mongo:5.0.9
        ports:
            - 27017:27017
        restart: always
        entrypoint:
            [
                '/usr/bin/mongod',
                '--bind_ip_all',
                '--replSet',
                'dbrs',
                '--dbpath',
                '/data/db',
                '--port',
                '27017',
            ]
        volumes:
            - ./.volumes/mongo/replica1:/data/db
            - ./.volumes/mongo/replica1/configdb:/data/configdb
        networks:
            - mongo_network
    mongo_replica_2:
        container_name: mongo_replica_2
        image: mongo:5.0.9
        ports:
            - 27018:27018
        restart: always
        entrypoint:
            [
                '/usr/bin/mongod',
                '--bind_ip_all',
                '--replSet',
                'dbrs',
                '--dbpath',
                '/data/db',
                '--port',
                '27018',
            ]
        volumes:
            - ./.volumes/mongo/replica2:/data/db
            - ./.volumes/mongo/replica2/configdb:/data/configdb
        networks:
            - mongo_network
    mongo_replica_3:
        container_name: mongo_replica_3
        image: mongo:5.0.9
        ports:
            - 27019:27019
        restart: always
        entrypoint:
            [
                '/usr/bin/mongod',
                '--bind_ip_all',
                '--replSet',
                'dbrs',
                '--dbpath',
                '/data/db',
                '--port',
                '27019',
            ]
        volumes:
            - ./.volumes/mongo/replica3:/data/db
            - ./.volumes/mongo/replica3/configdb:/data/configdb
        networks:
            - mongo_network
    backend:
        container_name: backend
        build:
            context: ./docker
            dockerfile: Dockerfile.api-dev
            args:
                - API_NAME=backend
        env_file:
            - ./apps/backend/envs/.env.development
            - ./docker/envs/.env.development
        ports:
            - ${PORT}:${PORT}
        restart: always
        depends_on:
            - mongo_replica_1
            - mongo_replica_2
            - mongo_replica_3
        networks:
            - mongo_network
    cli-backend:
        container_name: cli-backend
        build:
            context: ./docker
            dockerfile: Dockerfile.api-dev
            args:
                - API_NAME=cli-backend
        env_file:
            - ./apps/cli-backend/envs/.env.development
            - ./docker/envs/.env.development
        ports:
            - ${PORT}:${PORT}
        restart: always
        depends_on:
            - mongo_replica_1
            - mongo_replica_2
            - mongo_replica_3
        networks:
            - mongo_network
    frontend:
        container_name: frontend
        build:
            context: ./docker
            dockerfile: Dockerfile.frontend-dev
        env_file:
            - ./apps/frontend/.env.development
        ports:
            - ${PORT}:${PORT}
        restart: always
        depends_on:
            - backend
            - cli-backend
        networks:
            - mongo_network
networks:
    mongo_network:
        driver: bridge
