version: '3.8'

services:
    mongo_launcher:
        container_name: mongo_launcher
        image: mongo:6.0.2
        restart: on-failure
        networks:
            - dashboard_network
        volumes:
            - ./docker/scripts/mongo-setup.sh:/scripts/mongo-setup.sh
        entrypoint: ['sh', '/scripts/mongo-setup.sh']
    mongo_replica_1:
        container_name: mongo_replica_1
        image: mongo:6.0.2
        ports:
            - 27017:27017
        restart: always
        entrypoint:
            [
                '/usr/bin/mongod',
                '--bind_ip_all',
                '--replSet',
                'dbrs',
                '--dbpath',
                '/data/db',
                '--port',
                '27017',
            ]
        volumes:
            - ./.volumes/mongo/replica1:/data/db
            - ./.volumes/mongo/replica1/configdb:/data/configdb
        networks:
            - dashboard_network
    mongo_replica_2:
        container_name: mongo_replica_2
        image: mongo:6.0.2
        ports:
            - 27018:27018
        restart: always
        entrypoint:
            [
                '/usr/bin/mongod',
                '--bind_ip_all',
                '--replSet',
                'dbrs',
                '--dbpath',
                '/data/db',
                '--port',
                '27018',
            ]
        volumes:
            - ./.volumes/mongo/replica2:/data/db
            - ./.volumes/mongo/replica2/configdb:/data/configdb
        networks:
            - dashboard_network
    mongo_replica_3:
        container_name: mongo_replica_3
        image: mongo:6.0.2
        ports:
            - 27019:27019
        restart: always
        entrypoint:
            [
                '/usr/bin/mongod',
                '--bind_ip_all',
                '--replSet',
                'dbrs',
                '--dbpath',
                '/data/db',
                '--port',
                '27019',
            ]
        volumes:
            - ./.volumes/mongo/replica3:/data/db
            - ./.volumes/mongo/replica3/configdb:/data/configdb
        networks:
            - dashboard_network
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: ./docker/Dockerfile.backend-dev
        env_file:
            - ./apps/backend/envs/.env.development
            - ./docker/envs/.env.development
        ports:
            - 3000:3000
        restart: always
        depends_on:
            - mongo_replica_1
            - mongo_replica_2
            - mongo_replica_3
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ./apps/backend/src
              target: /dashboard/apps/backend/src
    cli-backend:
        container_name: cli-backend
        build:
            context: .
            dockerfile: ./docker/Dockerfile.cli-backend-dev
        env_file:
            - ./apps/cli-backend/envs/.env.development
            - ./docker/envs/.env.development
        ports:
            - 4000:4000
        restart: always
        depends_on:
            - mongo_replica_1
            - mongo_replica_2
            - mongo_replica_3
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ./apps/cli-backend/src
              target: /dashboard/apps/cli-backend/src
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: ./docker/Dockerfile.frontend-dev
        env_file:
            - ./apps/frontend/.env.development
        ports:
            - 8080:8080
        restart: always
        depends_on:
            - backend
            - cli-backend
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ./apps/frontend/src
              target: /dashboard/apps/frontend/src
networks:
    dashboard_network:
        driver: bridge
