# This is a template file for k8s deployment for a cli-backend deyployment
# Variables should be injected (and will be using "envsubst" GH Action) using GH Action
# This file won't be used explicitly with "kubectl"
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dashboard-cli-backend-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: dashboard-cli-backend
    template:
        metadata:
            labels:
                app: dashboard-cli-backend
        spec:
            containers:
                - name: dashboard-cli-backend
                  image: '$CLI_BACKEND_IMAGE'
                  imagePullPolicy: Always
                  env:
                      - name: NODE_ENV
                        value: '$NODE_ENV'
                      - name: PORT
                        value: '$PORT'
                      - name: FRONTEND_URL
                        value: '$FRONTEND_URL'
                      - name: CLI_TOKEN_JWT_KEY
                        value: '$CLI_TOKEN_JWT_KEY'
                      - name: REFRESH_TOKEN_JWT_KEY
                        value: '$REFRESH_TOKEN_JWT_KEY'
                      - name: MIXPANEL_TOKEN
                        value: '$MIXPANEL_TOKEN'
