FROM node:18

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/frontend/package.json ./apps/frontend/
COPY ./apps/frontend/patches ./apps/frontend/patches
COPY ./packages/common/package.json ./packages/common/

RUN pnpm i -w
RUN pnpm --filter frontend i

COPY ./tsconfig.base.json ./nx.json ./
COPY ./apps/frontend/ ./apps/frontend/

CMD ["pnpm", "exec", "nx", "start:dev:docker", "@exlint-dashboard/frontend"]
