FROM node:18.14.1

RUN npm i -g pnpm@7.27.1

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/backend/package.json ./apps/backend/
COPY ./packages/common/package.json ./packages/common/
COPY ./prisma/schema.prisma ./prisma/

RUN PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pnpm i -w
RUN pnpm --filter backend i

COPY ./tsconfig.base.json ./nx.json ./
COPY ./apps/backend/ ./apps/backend/

CMD ["pnpm", "exec", "nx", "start:dev:docker", "@exlint.io/backend"]
