FROM node:16

ARG API_NAME

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /dashboard

COPY ./package.json ./
COPY ./apps/${API_NAME}/package.json ./apps/${API_NAME}/

RUN pnpm install

COPY ./ ./

RUN cd ./apps/${API_NAME}
RUN pnpm build

CMD ["pnpm", "--filter", "${API_NAME}", "start:prod"]
