FROM node:18

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/backend/package.json ./apps/backend/
COPY ./prisma/schema.prisma ./prisma/

RUN pnpm add -D @prisma/client -w
RUN pnpm --filter backend i

COPY ./ ./

CMD ["pnpm", "--filter", "backend", "start:dev:docker"]
