FROM node:18.15.0

RUN npm i -g pnpm@7.30.3

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./tsconfig.base.json ./.npmrc ./
COPY ./apps/backend/package.json ./apps/backend/tsconfig.json ./apps/backend/tsconfig.base.json ./apps/backend/
COPY ./packages/common/package.json ./packages/common/tsconfig.base.json ./packages/common/tsconfig.build.json ./packages/common/
COPY ./prisma/schema.prisma ./prisma/

RUN PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pnpm i -w
RUN pnpm --filter backend --filter common i

COPY ./apps/backend/ ./apps/backend/
COPY ./packages/common/ ./packages/common/

RUN pnpm exec nx build @exlint.io/common
RUN pnpm exec nx build @exlint.io/backend

CMD ["node", "./apps/backend/dist/main.js"]
