FROM node:18

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/backend/package.json ./apps/backend/
COPY ./packages/common/package.json ./packages/common/
COPY ./prisma/schema.prisma ./prisma/

RUN pnpm i -w
RUN pnpm --filter backend i
RUN pnpm exec nx build @exlint-dashboard/backend

COPY ./apps/backend/ ./apps/backend/

CMD ["node", "./apps/backend/dist/main.js"]
