FROM node:18.14.0

RUN npm i -g pnpm@7.26.3

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./packages/common/package.json ./packages/common/
COPY ./prisma/schema.prisma ./prisma/

RUN PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pnpm i -w
RUN pnpm --filter common i

COPY ./tsconfig.base.json ./nx.json ./
COPY ./packages/common/ ./packages/common/

CMD ["pnpm", "exec", "nx", "start:dev", "@exlint.io/common"]
