FROM node:18

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./tsconfig.base.json ./.npmrc ./
COPY ./apps/frontend/package.json ./apps/frontend/tsconfig.json ./apps/frontend/tsconfig.base.json ./apps/frontend/tsconfig.json ./apps/frontend/
COPY ./packages/common/package.json ./packages/common/tsconfig.base.json ./packages/common/tsconfig.build.json ./packages/common/
COPY ./prisma/schema.prisma ./prisma/

RUN pnpm i -w
RUN pnpm --filter frontend --filter common i

COPY ./apps/frontend/ ./apps/frontend/
COPY ./packages/common/ ./packages/common/

RUN pnpm exec nx build:automation @exlint.io/frontend

CMD ["pnpm", "--filter", "frontend", "preview"]
