FROM node:16

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /monorepo

COPY ./package.json ./
COPY ./apps/frontend/package.json ./apps/frontend/

RUN pnpm install

COPY ./ ./

CMD ["pnpm", "--filter", "frontend", "start"]
