FROM node:18.15.0

RUN npm i -g pnpm@8.1.0

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/cli-backend/package.json ./apps/cli-backend/
COPY ./packages/common/package.json ./packages/common/
COPY ./prisma/schema.prisma ./prisma/

RUN PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pnpm i -w
RUN pnpm --filter cli-backend i

COPY ./tsconfig.base.json ./nx.json ./
COPY ./apps/cli-backend/ ./apps/cli-backend/

CMD ["pnpm", "exec", "nx", "start:dev:docker", "@exlint.io/cli-backend"]
