FROM node:18

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./packages/common/package.json ./packages/common/

RUN pnpm i -w
RUN pnpm --filter common i

COPY ./tsconfig.base.json ./nx.json ./
COPY ./packages/common/ ./packages/common/

CMD ["pnpm", "exec", "nx", "start:dev", "@exlint-dashboard/common"]
