FROM node:18

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/frontend/package.json ./apps/frontend/
COPY ./packages/common/package.json ./packages/common/

RUN pnpm --filter frontend --filter common i

COPY ./tsconfig.base.json  ./
COPY ./apps/frontend/ ./apps/frontend/
COPY ./packages/common/ ./packages/common/

CMD ["pnpm", "exec", "nx", "start:dev:docker", "@exlint-dashboard/frontend"]
