FROM node:18.18.2

RUN npm i -g pnpm@8.11.0

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./tsconfig.base.json ./.npmrc ./
COPY ./apps/frontend/package.json ./apps/frontend/tsconfig.json ./apps/frontend/tsconfig.base.json ./apps/frontend/
COPY ./packages/common/package.json ./packages/common/tsconfig.base.json ./packages/common/tsconfig.build.json ./packages/common/
COPY ./prisma/schema.prisma ./prisma/

RUN PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pnpm i -w
RUN pnpm --filter frontend --filter common i

COPY ./apps/frontend/ ./apps/frontend/
COPY ./packages/common/ ./packages/common/

RUN pnpm exec nx build:automation @exlint.io/frontend

CMD ["pnpm", "--filter", "frontend", "preview:automation"]
