FROM node:18

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/backend/package.json ./apps/backend/
COPY ./packages/common/package.json ./packages/common/
COPY ./prisma/schema.prisma ./prisma/

RUN pnpm --filter backend --filter common i

COPY ./tsconfig.base.json  ./
COPY ./apps/backend/ ./apps/backend/
COPY ./packages/common/ ./packages/common/

CMD ["pnpm", "exec", "nx", "start:dev:docker", "@exlint-dashboard/backend"]
