FROM node:19

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/cli-backend/package.json ./apps/cli-backend/
COPY ./prisma/schema.prisma ./prisma/

RUN pnpm --filter cli-backend i

COPY ./tsconfig.base.json  ./
COPY ./apps/cli-backend/ ./apps/cli-backend/

CMD ["pnpm", "--filter", "cli-backend", "start:dev:docker"]
