project              = "ExlintDashboard"
node_env             = "production"
backend_api_host     = "api.exlint.io"
cli_backend_api_host = "cli-api.exlint.io"
frontend_url         = "https://app.exlint.io"
