name: Deploy to frontend S3

on:
    push:
        paths:
            - './apps/frontend/**/*'
            - './packages/common/**/*'
        branches:
            - PRODUCTION

jobs:
    deploy:
        runs-on: [self-hosted, linux, x64, deploy]
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18.12.1
                  package-manager: pnpm
                  package-manager-version: 7.20.0

            - name: Build frontend
              run: 'pnpm exec nx build @exlint-dashboard/frontend'

            - name: Deploy to S3 and invalidate Cloudfront
              uses: reggionick/s3-deploy@v3
              with:
                  folder: ./apps/frontend/dist
                  bucket: ${{ secrets.AWS_S3_BUCKET }}
                  bucket-region: eu-west-1
                  dist-id: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
                  invalidation: /*
                  delete-removed: true
                  private: true
                  filesToInclude: '**/*'
