name: Lint Commit Messages
on: [pull_request]

jobs:
    commitlint:
        name: Commitlint
        permissions:
            contents: read
            pull-requests: read

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  
            - uses: wagoid/commitlint-github-action@v5
