name: Lint Commit Messages

on:
  pull_request:
    branches-ignore:    
      - PRODUCTION


jobs:
    commitlint:
        name: Commitlint
        permissions:
            contents: read
            pull-requests: read

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  
            - uses: wagoid/commitlint-github-action@v5
