name: Deploy docs application

on:
  repository_dispatch:
    types: [docs-production]

jobs:
    deploy:
        name: Deploy docs to AWS
        runs-on: [self-hosted, Linux, X64, deploy]

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.4
              with:
                  should-cache: false
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.26.3
                  sub-modules: true

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Build docs
              run: pnpm exec nx build @exlint.io/docs

            - name: Deploy to S3 and invalidate Cloudfront
              uses: reggionick/s3-deploy@v3
              with:
                  folder: ./apps/docs/build
                  bucket: ${{ secrets.DOCS_AWS_S3_BUCKET }}
                  bucket-region: ${{ secrets.AWS_REGION }}
                  dist-id: ${{ secrets.DOCS_AWS_CLOUDFRONT_DISTRIBUTION_ID }}
                  invalidation: /
                  delete-removed: true
                  private: true
                  filesToInclude: '**/*'

            - name: Slack notification                                
              uses: rtCamp/action-slack-notify@v2             
              env:                                                    
                SLACK_CHANNEL: dashboard-deployment       
                SLACK_MESSAGE: 'Just deployed docs'
                SLACK_TITLE: 'Deployment'                         
                SLACK_USERNAME: 'Yazif Deployer'                           
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_DASHBOARD_DEPLOYMENT }}       
                MSG_MINIMAL: true  
