name: Deploy frontend application

on:
  push:
    branches:
      - PRODUCTION
    paths:
      - apps/frontend/**
      - packages/common/**

jobs:
    deploy:
        name: Deploy frontend to AWS
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  should-cache: false
                  node-version: 20.18.1
                  package-manager: pnpm
                  package-manager-version: 8.15.9

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Build frontend
              run: pnpm exec nx build @exlint.io/frontend

            - name: Deploy to S3 and invalidate Cloudfront
              uses: reggionick/s3-deploy@v4
              with:
                  folder: ./apps/frontend/dist
                  bucket: ${{ secrets.FRONTEND_AWS_S3_BUCKET }}
                  bucket-region: ${{ secrets.AWS_REGION }}
                  dist-id: ${{ secrets.FRONTEND_AWS_CLOUDFRONT_DISTRIBUTION_ID }}
                  invalidation: /
                  delete-removed: true
                  private: true
                  filesToInclude: '**/*'

            - name: Slack notification                                
              uses: rtCamp/action-slack-notify@v2             
              env:                                                    
                SLACK_CHANNEL: dashboard-deployment       
                SLACK_MESSAGE: 'Just deployed frontend'
                SLACK_TITLE: 'Deployment'                         
                SLACK_USERNAME: 'Yazif Deployer'                           
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_DASHBOARD_DEPLOYMENT }}       
                MSG_MINIMAL: true  
