name: Destroy Terrafrom

on:
  workflow_dispatch:

jobs:
    destroy_terraform:
        name: Destroy Terraform 
        runs-on: ubuntu-latest
        if: github.actor == 'tal-rofe'
        env:
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_frontend_s3_bucket_name: ${{ secrets.FRONTEND_AWS_S3_BUCKET }}
            TF_VAR_docs_s3_bucket_name: ${{ secrets.DOCS_AWS_S3_BUCKET }}
            TF_VAR_landing_page_s3_bucket_name: ${{ secrets.LANDING_PAGE_AWS_S3_BUCKET }}
            TF_VAR_backend_repository: dashboard-backend
            TF_VAR_cli_backend_repository: dashboard-cli-backend
            TF_VAR_database_url: mongodb+srv://${{ secrets.DATABASE_USERNAME }}:${{ secrets.DATABASE_PASSWORD }}@dashboard.elge3qb.mongodb.net/dashboard?retryWrites=true&w=majority
            TF_VAR_access_token_jwt_key: ${{ secrets.ACCESS_TOKEN_JWT_KEY }}
            TF_VAR_refresh_token_jwt_key: ${{ secrets.REFRESH_TOKEN_JWT_KEY }}
            TF_VAR_google_oauth_client_id: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
            TF_VAR_google_oauth_client_secret: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
            TF_VAR_google_oauth_redirect_uri: "https://api.exlint.io/user/auth/google-redirect"
            TF_VAR_gh_oauth_client_id: ${{ secrets.GH_OAUTH_CLIENT_ID }}
            TF_VAR_gh_oauth_client_secret: ${{ secrets.GH_OAUTH_CLIENT_SECRET }}
            TF_VAR_gh_oauth_redirect_uri: "https://api.exlint.io/user/auth/github-redirect"
            TF_VAR_mixpanel_token: ${{ secrets.MIXPANEL_TOKEN }}
            TF_VAR_frontend_url: "https://app.exlint.io"
            TF_VAR_cli_token_jwt_key: ${{ secrets.CLI_TOKEN_JWT_KEY }}

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  should-cache: false
                  node-version: 18.16.0
                  package-manager: pnpm
                  package-manager-version: 8.6.6

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Get package.json version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@main

            - name: Terraform setup
              uses: hashicorp/setup-terraform@v2

            - name: Terraform k8s init
              working-directory: terraform/k8s
              env:
                  TERRAFORM_BACKEND_S3_BUCKET: ${{ secrets.TERRAFORM_BACKEND_S3_BUCKET }}
                  TERRAFORM_BACKEND_DYNAMODB_TABLE: ${{ secrets.TERRAFORM_BACKEND_DYNAMODB_TABLE }}
              run: |
                terraform init \
                -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" \
                -backend-config="dynamodb_table=$TERRAFORM_BACKEND_DYNAMODB_TABLE" \
                -backend-config="region=$AWS_REGION" 

            - name: Terraform k8s destroy
              working-directory: terraform/k8s
              env:
                TF_VAR_api_image_tag: ${{ steps.package-version.outputs.current-version }}
              run: terraform destroy -auto-approve

            - name: Terraform core init
              working-directory: terraform/core
              env:
                  TERRAFORM_BACKEND_S3_BUCKET: ${{ secrets.TERRAFORM_BACKEND_S3_BUCKET }}
                  TERRAFORM_BACKEND_DYNAMODB_TABLE: ${{ secrets.TERRAFORM_BACKEND_DYNAMODB_TABLE }}
              run: |
                terraform init \
                -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" \
                -backend-config="dynamodb_table=$TERRAFORM_BACKEND_DYNAMODB_TABLE" \
                -backend-config="region=$AWS_REGION" 

            - name: Terraform core destroy
              working-directory: terraform/core
              run: terraform destroy -auto-approve
