name: Integration

on:
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    call_pnpm_caching_workflow:
        name: Set PNPM environment

        uses: ./.github/workflows/pnpm-caching.yaml
        with:
            runner: [self-hosted, Linux, X64, integration]

    test_depcheck:
        needs: call_pnpm_caching_workflow
        name: Testing Depcheck

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.20.0

            - name: Test Depcheck
              run: pnpm depcheck:all

    test_inflint:
        needs: call_pnpm_caching_workflow
        name: Testing Inflint

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.20.0

            - name: Test Inflint
              run: pnpm inflint

    test_typescript:
        needs: call_pnpm_caching_workflow
        name: Testing TypeScript

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.20.0

            - name: Test TypeScript
              run: pnpm type-check:all

    test_prettier:
        needs: call_pnpm_caching_workflow
        name: Testing Prettier

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.20.0

            - name: Test Prettier
              run: pnpm prettier

    test_eslint:
        needs: call_pnpm_caching_workflow
        name: Testing ESLint

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.20.0

            - name: Test ESLint
              run: pnpm lint:all

    test_stylelint:
        needs: call_pnpm_caching_workflow
        name: Testing Stylelint

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.20.0

            - name: Test Stylelint
              run: pnpm nx stylelint @exlint-dashboard/frontend

    test_prisma:
        needs: call_pnpm_caching_workflow
        name: Testing Prisma

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.20.0

            - name: Test Prisma
              run: pnpm prisma-format

    test_build:
        needs: call_pnpm_caching_workflow
        name: Testing build

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.20.0

            - name: Test build
              run: pnpm build:nested

    test_terraform:
        name: Testing Terraform

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}
                  
            - name: Terraform setup
              uses: hashicorp/setup-terraform@v2

            - name: Terraform init
              env:
                  TERRAFORM_BACKEND_S3_BUCKET: ${{ secrets.TERRAFORM_BACKEND_S3_BUCKET }}
                  TERRAFORM_BACKEND_DYNAMODB_TABLE: ${{ secrets.TERRAFORM_BACKEND_DYNAMODB_TABLE }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
              run: |
                terraform -chdir="./terraform" init \
                -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" \
                -backend-config="dynamodb_table=$TERRAFORM_BACKEND_DYNAMODB_TABLE" \
                -backend-config="region=$AWS_REGION" 

            - name: Terraform validate
              run: terraform -chdir="./terraform" validate -no-color