name: Integration

on:
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    call_pnpm_caching_workflow:
        name: Set PNPM environment

        uses: ./.github/workflows/pnpm-caching.yaml
        with:
            runner: [self-hosted, Linux, X64, integration]

    depcheck:
        needs: call_pnpm_caching_workflow
        name: Testing Depcheck

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.25.1

            - name: Test Depcheck
              run: pnpm depcheck:all

    inflint:
        needs: call_pnpm_caching_workflow
        name: Testing Inflint

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.25.1

            - name: Test Inflint
              run: pnpm inflint

    typescript:
        needs: call_pnpm_caching_workflow
        name: Testing TypeScript

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.25.1

            - name: Test TypeScript
              run: pnpm type-check:all

    prettier:
        needs: call_pnpm_caching_workflow
        name: Testing Prettier

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.25.1

            - name: Test Prettier
              run: pnpm prettier

    eslint:
        needs: call_pnpm_caching_workflow
        name: Testing ESLint

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.25.1

            - name: Test ESLint
              run: pnpm lint:all

    stylelint:
        needs: call_pnpm_caching_workflow
        name: Testing Stylelint

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.25.1

            - name: Test Stylelint
              run: pnpm nx stylelint @exlint-dashboard/frontend

    prisma:
        needs: call_pnpm_caching_workflow
        name: Testing Prisma

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.25.1

            - name: Test Prisma
              run: pnpm prisma-format

    build:
        needs: call_pnpm_caching_workflow
        name: Testing build

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.25.1

            - name: Test build
              run: pnpm build:nested

    terraform:
        name: Testing Terraform

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}
                  
            - name: Terraform setup
              uses: hashicorp/setup-terraform@v2

            - name: Terraform init
              env:
                  TERRAFORM_BACKEND_S3_BUCKET: ${{ secrets.TERRAFORM_BACKEND_S3_BUCKET }}
                  TERRAFORM_BACKEND_DYNAMODB_TABLE: ${{ secrets.TERRAFORM_BACKEND_DYNAMODB_TABLE }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
              run: |
                terraform -chdir="./terraform" init \
                -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" \
                -backend-config="dynamodb_table=$TERRAFORM_BACKEND_DYNAMODB_TABLE" \
                -backend-config="region=$AWS_REGION" 

            - name: Terraform validate
              run: terraform -chdir="./terraform" validate -no-color

    automation:
        timeout-minutes: 60
        needs: call_pnpm_caching_workflow
        name: Automation Tests

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            - name: Run Playwright tests
              run: pnpm test

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30