name: Integration

on:
    pull_request:
        branches: [main]

jobs:
    call_pnpm_caching_workflow:
        name: Set pnpm caching
        uses: ./.github/workflows/pnpm-caching.yaml
        with:
            runner: ubuntu-latest
            node-version: 18
            pnpm-version: 7.14.0

    test_depcheck:
        needs: call_pnpm_caching_workflow
        name: Testing Depcheck
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18.12.0
                  package-manager: pnpm
                  package-manager-version: 7.14.0

            - name: Test Depcheck
              run: pnpm depcheck && pnpm -r --parallel depcheck

    test_inflint:
        needs: call_pnpm_caching_workflow
        name: Testing Inflint
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18.12.0
                  package-manager: pnpm
                  package-manager-version: 7.14.0

            - name: Test Inflint
              run: pnpm inflint

    test_typescript:
        needs: call_pnpm_caching_workflow
        name: Testing TypeScript
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18.12.0
                  package-manager: pnpm
                  package-manager-version: 7.14.0

            - name: Test TypeScript
              run: pnpm type-check && pnpm -r --parallel type-check

    test_prettier:
        needs: call_pnpm_caching_workflow
        name: Testing Prettier
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18.12.0
                  package-manager: pnpm
                  package-manager-version: 7.14.0

            - name: Test Prettier
              run: pnpm prettier

    test_eslint:
        needs: call_pnpm_caching_workflow
        name: Testing ESLint
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18.12.0
                  package-manager: pnpm
                  package-manager-version: 7.14.0

            - name: Test ESLint
              run: pnpm lint && pnpm -r --parallel lint

    test_stylelint:
        needs: call_pnpm_caching_workflow
        name: Testing Stylelint
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18.12.0
                  package-manager: pnpm
                  package-manager-version: 7.14.0

            - name: Test Stylelint
              run: pnpm --filter frontend stylelint

    test_prisma:
        needs: call_pnpm_caching_workflow
        name: Testing Prisma
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18.12.0
                  package-manager: pnpm
                  package-manager-version: 7.14.0

            - name: Test Prisma
              run: pnpm prisma-format

    test_build:
        needs: call_pnpm_caching_workflow
        name: Testing build
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18.12.0
                  package-manager: pnpm
                  package-manager-version: 7.14.0

            - name: Test build
              run: pnpm -r --parallel build
