name: Integration

on:
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    depcheck:
        name: Testing Depcheck

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.19.0
                  package-manager: pnpm
                  package-manager-version: 8.11.0

            - name: Test Depcheck
              run: pnpm depcheck:all

    inflint:
        name: Testing Inflint

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.19.0
                  package-manager: pnpm
                  package-manager-version: 8.11.0

            - name: Test Inflint
              run: pnpm inflint

    typescript:
        name: Testing TypeScript

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.19.0
                  package-manager: pnpm
                  package-manager-version: 8.11.0

            - name: Test TypeScript
              run: pnpm type-check:all

    prettier:
        name: Testing Prettier

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.19.0
                  package-manager: pnpm
                  package-manager-version: 8.11.0

            - name: Test Prettier
              run: pnpm prettier

    eslint:
        name: Testing ESLint

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.19.0
                  package-manager: pnpm
                  package-manager-version: 8.11.0

            - name: Test ESLint
              run: pnpm lint:all

    stylelint:
        name: Testing Stylelint

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.19.0
                  package-manager: pnpm
                  package-manager-version: 8.11.0

            - name: Test Stylelint
              run: pnpm exec nx run-many --target=stylelint --nx-bail

    prisma:
        name: Testing Prisma

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.19.0
                  package-manager: pnpm
                  package-manager-version: 8.11.0

            - name: Test Prisma
              run: pnpm prisma-format

    build:
        name: Testing build

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.19.0
                  package-manager: pnpm
                  package-manager-version: 8.11.0

            - name: Test build
              run: pnpm build:nested

    cspell:
      name: CSpell
      runs-on: ubuntu-latest

      steps:
          - name: Setup Node environment
            uses: Exlint/node-environment@v1.2.6
            with:
                node-version: 18.19.0
                package-manager: pnpm
                package-manager-version: 8.11.0

          - name: CSpell
            run: pnpm cspell