name: Reusable pnpm caching workflow

on:
    workflow_call:
        inputs:
            runner:
                required: true
                type: string
            node-version:
                required: true
                type: string
            pnpm-version:
                required: true
                type: string

jobs:
    install_dependencies:
        name: Install dependencies and caching
        runs-on: ${{ inputs.runner }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node environment
              uses: ./.github/actions/setup-node-environment
              with:
                  node-version: ${{ inputs.node-version }}
                  pnpm-version: ${{ inputs.pnpm-version }}
