name: Reusable pnpm caching workflow

on:
    workflow_call:
        inputs:
            runner:
                required: true
                type: string

jobs:
    install_dependencies:
        name: Install dependencies and caching
        permissions:
            contents: read

        runs-on: ${{ inputs.runner }}
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.1.0
              with:
                  should-cache: false
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.20.0
