name: Reusable pnpm caching workflow

on:
    workflow_call:
        inputs:
            runner:
                required: true
                type: string
            node-version:
                required: true
                type: string
            pnpm-version:
                required: true
                type: string

jobs:
    install_dependencies:
        name: Install dependencies and caching
        runs-on: ${{ inputs.runner }}
        strategy:
            matrix:
                node-version: ['${{ inputs.node-version }}']
                pnpm-version: ['${{ inputs.pnpm-version }}']

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: ${{ matrix.pnpm-version }}

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Installing dependencies
              run: pnpm i --frozen-lockfile
